general:
steps:
  onapsisExecuteScan:
    scanServiceUrl: 'https://awslabsap1079.orl.onapsis.com:30443'
    scanGitUrl: 'https://github.com/mergenhan/UI5_vulnerable_design.git'
    scanGitBranch: 'jenkins-file'
    appType: 'SAPUI5'
    failOnOptionalFinding: true